version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

  redis:
    image: redis:alpine
    networks:
      - wp-network

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
      - redis
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CACHE_HOST: redis
    deploy:
      replicas: 2
    networks:
      - wp-network

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./wp-nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
    driver: bridge