# Version de la syntaxe Docker Compose
version: '3.8'

# Déclaration des services
services:
  # Service pour l'environnement de développement
  api:
    build:
      # Utilise le répertoire courant comme contexte de build
      context: .       
      # Fichier Dockerfile pour le build single-stage   
      dockerfile: dockerfile.multistage  
    image: api-ping-prod:1.0      
    environment:
      - PING_LISTEN_PORT=3000
      # Environnement de production
      - NODE_ENV=production  

    # Connexion au réseau dédié     
    networks:
      - ping-network
    deploy:
      replicas: 4    
    
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - ping-network

networks:
  ping-network:
    driver: bridge